apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kridge.kusionstack.io/ignore-webhook: 'true'
  name: kridge
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      control-plane: kridge
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        control-plane: kridge
        kridge.kusionstack.io/ignore-webhook: 'true'
        kridge.kusionstack.io/watching: 'true'
    spec:
      containers:
        - args:
            - --logtostderr=true
            - --v=4
            - --leader-election-namespace={{ .Values.namespace }}
            - --proxy-image={{ .Values.proxyImage.repository }}:{{ .Values.proxyImage.tag }}
            - --proxy-cpu={{ .Values.proxyResources.cpu }}
            - --proxy-memory={{ .Values.proxyResources.memory }}
            - --proxy-ephemeral-storage={{ .Values.proxyResources.ephemeralStorage }}
            - --proxy-image-pull-policy=IfNotPresent
          command:
            - /kridge-manager
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: ENABLE_WEBHOOK_SERVER
              value: 'true'
            - name: WEBHOOK_CERT_WRITER
              value: secret
            - name: WATCH_ON_LIMIT
              value: 'true'
          image: {{ .Values.managerImage.repository }}:{{ .Values.managerImage.tag }}
          imagePullPolicy: {{ .Values.managerImage.pullPolicy }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          name: manager
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /delay
              port: 8083
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            {{- toYaml .Values.managerResources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      serviceAccount: kridge-serviceaccount
      serviceAccountName: kridge-serviceaccount